<a href="https://colab.research.google.com/github/lobabahsaad/pythonFundamentalz/blob/main/python_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
name = 'Lionel Messi'
print("My favorite player is",name)

birth_year = 1987
print("He was born in",birth_year)

height = 5 + (7/12)
print("He is",height,"feet tall")

GOAT = True
print("Is he the Greatest Of All Time?",GOAT) 

print(type(name))
print(type(birth_year))
print(type(height))
print(type(GOAT))


My favorite player is Lionel Messi
He was born in 1987
He is 5.583333333333333 feet tall
Is he the Greatest Of All Time? True
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


**String Manipulation**

In [ ]:
name = "ronaldo"
updated_name = name.capitalize()

print(updated_name)

Ronaldo


In [ ]:
name_count = name.count("o")

print(name_count)

2


In [ ]:
name_startswith = name.startswith("r")
print(name_startswith)

name_endswith = name.endswith("r")
print(name_endswith)

True
False


In [ ]:
var = "I love Russia"

print(var[0])
print(var[1])
print(var[2])


print(var[1])

print(var[-1])

print(var[2:6])
print(var[7:13])




I
 
l
 
a
love
Russia


In [ ]:
print(len(var))

13


In [5]:
text = "Happy New Year"

print(text.find("Y"))
print(text.index("a"))

10
1


In [7]:
name = "Shakib Al Hasan"

print(name.upper())
print(name.lower())

SHAKIB AL HASAN
shakib al hasan


In [9]:
text = "Haqqy New Year"

print(text.replace("q","p"))

Happy New Year


In [15]:
name = "ShakibAlHasan"

print(name.isalpha())
print(name.isupper())
print(name.islower())
print(name.isdigit())

True
False
False
False


**LECTURE 04**

LIST, TUPLE AND DICTIONARY

In [20]:
fam = ["abbu", 5.6, "ammu", 5, "me", 5.8, "wife", 5.4]

print(fam[1])
print(fam[0:2])
print(fam[4:6])
print(fam[-2:])
print(fam[:5])

5.6
['abbu', 5.6]
['me', 5.8]
['wife', 5.4]
['abbu', 5.6, 'ammu', 5, 'me']


In [21]:
len(fam)

8

In [23]:
print("abbu" in fam)
print("choto" in fam)

True
False


In [28]:
fam.append("choto")
fam.append(6.2)

print(fam)

['abbu', 5.6, 'ammu', 5, 'me', 5.8, 'wife', 5.4, 'choto', 'choto', 6.2, 'choto', 6.2]


In [29]:
fam.reverse()

print(fam)

[6.2, 'choto', 6.2, 'choto', 'choto', 5.4, 'wife', 5.8, 'me', 5, 'ammu', 5.6, 'abbu']


In [33]:
even = [4,2,8,-2,-6,10]

print(sorted(even, reverse=False))   #default #ascending order
print(sorted(even, reverse=True))    #descending order

[-6, -2, 2, 4, 8, 10]
[10, 8, 4, 2, -2, -6]


In [34]:
list_A = [1,2,3]
list_B = [4,5,6]

list = list_A + list_B
print(list)

[1, 2, 3, 4, 5, 6]


In [39]:
even = [4,2,8,-2,-6,10]

print(sum(even))
print(max(even))
print(min(even))

even.remove(-2)
print(even)

print(even.count(4))

16
10
-6
[4, 2, 8, -6, 10]
1


**TUPLE**

In [40]:
mov = ("the", "faults", "in", "our", "stars")

print(type(mov))

<class 'tuple'>


In [42]:
print(mov[:2])
print(mov[-1])

('the', 'faults')
stars


**SET**

In [43]:
a = {1,2,3,4}
b = {3,4,5,6}

In [48]:
#union
c = a.union(b)
print(c)

#intersection
d = a.intersection(b)
print(d)

#difference
e = a.difference(b)
f = b.difference(a)

print(e)
print(f)

{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{5, 6}


DICTIONARY

In [51]:
contacts = {"abul": 111,
            "babul": 222,
            "bipul": 333}

print(contacts)
print(contacts["babul"])
print(contacts.keys())
print(contacts.values())


{'abul': 111, 'babul': 222, 'bipul': 333}
222
dict_keys(['abul', 'babul', 'bipul'])
dict_values([111, 222, 333])


In [54]:
#updating contact info
contacts["bipul"] = [444,555]
print(contacts)

#enlisting new contact info
contacts["shakil"] = [789,456]

print(contacts)

{'abul': 111, 'babul': 222, 'bipul': [444, 555], 'shakil': 789}
{'abul': 111, 'babul': 222, 'bipul': [444, 555], 'shakil': [789, 456]}


In [57]:
#updating contact list
dic = {"rony" : 999}

contacts.update(dic)
print(contacts)

del contacts["bipul"]
print(contacts)


{'abul': 111, 'babul': 222, 'shakil': [789, 456], 'rony': 999}


**Lecture 05** 

LOOP

In [62]:
nums = [1,2,3,4,5,6]
sq_list = []

for item in nums:
  sq = item*item
  sq_list.append(sq)
  print("Item =", item,"Square =",sq_list)

print(sq_list)

Item = 1 Square = [1]
Item = 2 Square = [1, 4]
Item = 3 Square = [1, 4, 9]
Item = 4 Square = [1, 4, 9, 16]
Item = 5 Square = [1, 4, 9, 16, 25]
Item = 6 Square = [1, 4, 9, 16, 25, 36]
[1, 4, 9, 16, 25, 36]


WRITING FUNCTIONS

In [63]:
def add(input_1,input_2):
  output = input_1 + input_2
  return output

In [64]:
add(5,6)

11

In [69]:
def square(input_list):
  sq_list = []

  for item in input_list:
    sq = item*item
    sq_list.append(sq)
  return sq_list 


In [70]:
square([1,2,3,4,5,6])

[1, 4, 9, 16, 25, 36]

**IF ELSE CONDITION**

In [72]:
for i in range(1,11):
  if i%2 == 0:
    print(i,"is an EVEN number")
  else: 
    print(i,"is an ODD number")

1 is an ODD number
2 is an EVEN number
3 is an ODD number
4 is an EVEN number
5 is an ODD number
6 is an EVEN number
7 is an ODD number
8 is an EVEN number
9 is an ODD number
10 is an EVEN number


WHILE LOOP

In [73]:
c = 0
while c < 3:
  print("I love you")
  c = c+1

I love you
I love you
I love you


**Lecture 06**

Math Functions

In [3]:
import math

def powerOfTwo(n):
  x = math.log10(n)/math.log10(2)

  print(x)
  print(int(x))
  return n == 2**int(x)

In [6]:
example = powerOfTwo(13)
print(example)

3.700439718141092
3
False


In [7]:
def containDuplicate(nums):
  return len(nums) != len(set(nums)) 

In [9]:
example = containDuplicate([1,2,3,4])
print(example)

False


In [12]:
def twoSums(nums, target):
  dict = {}
  for i in range(len(nums)):
    goal = target - nums[i]

    if (goal in dict):
      return [dict[goal], i]

    dict[nums[i]] = i


In [13]:
example = twoSums([1,3,2],5)
print(example)

[1, 2]


In [15]:
example = twoSums([1,7,3,2],9)
print(example)

[1, 3]


**LECTURE 08**

NUMPY ARRAY

In [26]:
list_1 = [1,2,3,4,5,6,7,8,9]
list_2 = [4,54,6,7,8,9,10,12,14]

In [33]:
import numpy as np

In [29]:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

print(arr_1)
print(arr_2)

#addition
a_add = arr_1 + arr_2
print(a_add)

#subtraction
a_sub = arr_1 - arr_2
print(a_sub)

[1 2 3 4 5 6 7 8 9]
[ 4 54  6  7  8  9 10 12 14]
[ 5 56  9 11 13 15 17 20 23]
[ -3 -52  -3  -3  -3  -3  -3  -4  -5]


**2D ARRAY**

In [45]:
a1 = np.array([[1,2,3],
               [4,5,6]])
a2 = np.array([[1,2,3],
                  [4,5,6]])

print(a1)
print(a2)

#addition
a2d_add = np.add(a1,a2)
print("addition = \n",a2d_add)

#subtraction
a2d_sub = np.subtract(a1,a2)
print("subtraction = \n",a2d_sub)

#multiplication 
a2d_mul = np.multiply(a1,a2)
print("multiplication = \n",a2d_mul)

#division 
a2d_div = np.divide(a1,a2)
print("division = \n",a2d_div)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
addition = 
 [[ 2  4  6]
 [ 8 10 12]]
subtraction = 
 [[0 0 0]
 [0 0 0]]
multiplication = 
 [[ 1  4  9]
 [16 25 36]]
division = 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [54]:
a6 = np.array([2,2,2,2,2])
a7 = np.array([1,2,3,4,5])
a8 = np.array([1.05, -2, 3.5, -4, 7.75])


a_pow = np.power(a6, a7)
print(a_pow)

a_sqr = np.square(a7)
print(a_sqr)

a_abs = np.abs(a8)
print(a_abs)

[ 2  4  8 16 32]
[ 1  4  9 16 25]
[1.05 2.   3.5  4.   7.75]


CEILING, FLOORING AND ROUNDING

In [55]:
#a8 = np.array([1.05, -2, 3.5, -4, 7.25])

#ceiling
a_ceil = np.ceil(a8)
print(a_ceil) 

#flooring
a_floor = np.floor(a8)
print(a_floor)

#rounding
a_round = np.round(a8)
print(a_round)

[ 2. -2.  4. -4.  8.]
[ 1. -2.  3. -4.  7.]
[ 1. -2.  4. -4.  8.]


**SUM**

In [58]:
a6 = np.array([2,2,2,2,2])
a7 = np.array([1,2,3,4,5])

#array sum
a_sum = np.sum([a6,a7])
print("array sum =", a_sum)

#column sum
col_sum = np.sum([a6,a7], axis=0)
print("column sum =", col_sum)

#row sum
row_sum = np.sum([a6,a7], axis=1)
print("row sum =", row_sum)

array sum = 25
column sum = [3 4 5 6 7]
row sum = [10 15]


**PRODUCT**

In [60]:
a6 = np.array([2,2,2,2,2])
a7 = np.array([1,2,3,4,5])

#array product
a_prod = np.prod([a6,a7])
print("array product =", a_prod)

#column product
col_prod = np.sum([a6,a7], axis=0)
print("column product =", col_prod)

#row product
row_prod = np.sum([a6,a7], axis=1)
print("row product =", row_prod)

array product = 3840
column product = [3 4 5 6 7]
row product = [10 15]


Creating Matrix 

In [64]:
#identical matrix
identical_matrix = np.eye(3)
print(identical_matrix)

#one matrix
one_matrix = np.ones((3,3))
print(one_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Matrix Multiplication

In [67]:
#matrix multiplication
mat_mul = np.matmul(identical_matrix, one_matrix)
print(mat_mul)

#diagonal attributes
array_diag = np.diag(identical_matrix)
print(array_diag)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1.]


ARRAY INDEXING AND SLICING

In [82]:
a1 = np.array([[1,2,3],
               [4,5,6]])

print(a1.shape)
print(a1[1])


(2, 3)
[4 5 6]


**LECTURE 08**

DATA ANALYSIS IN PYTHON: PANDAS

In [83]:
#reading a csv file as DataFrame

import pandas as pd
df = pd.read_csv("telecom_data.csv")

In [84]:
display(df)

Account_Length  Vmail_Message  CustServ_Calls Churn Intl_Plan  \
0                128             25               1    no        no   
1                107             26               1    no        no   
2                137              0               0    no        no   
3                 84              0               2    no       yes   
4                 75              0               3    no       yes   
...              ...            ...             ...   ...       ...   
3328             192             36               2    no        no   
3329              68              0               3    no        no   
3330              28              0               2    no        no   
3331             184              0               2    no       yes   
3332              74             25               0    no        no   

     Vmail_Plan  Total_mins  Total_calls  Total_charges  
0           yes       717.2          303         320.26  
1           yes       625.2          332         313.64  
2            no       539.4          333         224.89  
3            no       564.8          255         263.70  
4            no       512.0          359         238.99  
...         ...         ...          ...            ...  
3328        yes       660.7          292         339.20  
3329         no       585.4          239         254.83  
3330         no       675.6          264         259.64  
3331         no       517.6          336         196.73  
3332        yes       755.4          276         318.41  

[3333 rows x 9 columns]

In [85]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [87]:
print(df.shape)
print("number of rows =",df.shape[0])
print("number of columns =",df.shape[1])

(3333, 9)
number of rows = 3333
number of columns = 9


# Check the coloumn types & Look for missing values

In [88]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Account_Length  3333 non-null   int64  
 1   Vmail_Message   3333 non-null   int64  
 2   CustServ_Calls  3333 non-null   int64  
 3   Churn           3333 non-null   object 
 4   Intl_Plan       3333 non-null   object 
 5   Vmail_Plan      3333 non-null   object 
 6   Total_mins      3333 non-null   float64
 7   Total_calls     3333 non-null   int64  
 8   Total_charges   3333 non-null   float64
dtypes: float64(2), int64(4), object(3)
memory usage: 234.5+ KB
None


In [89]:
df["Churn"].value_counts()

no     2850
yes     483
Name: Churn, dtype: int64

In [90]:
df["Intl_Plan"].value_counts()

no     3010
yes     323
Name: Intl_Plan, dtype: int64

In [91]:
df["Vmail_Plan"].value_counts()

no     2411
yes     922
Name: Vmail_Plan, dtype: int64

In [93]:
display(df.describe())

Account_Length  Vmail_Message  CustServ_Calls   Total_mins  \
count     3333.000000    3333.000000     3333.000000  3333.000000   
mean       101.064806       8.099010        1.562856   591.864776   
std         39.822106      13.688365        1.315491    89.954251   
min          1.000000       0.000000        0.000000   284.300000   
25%         74.000000       0.000000        1.000000   531.500000   
50%        101.000000       0.000000        1.000000   593.600000   
75%        127.000000      20.000000        2.000000   652.400000   
max        243.000000      51.000000        9.000000   885.000000   

       Total_calls  Total_charges  
count  3333.000000    3333.000000  
mean    305.137114     260.321791  
std      34.448164      53.810896  
min     191.000000      68.370000  
25%     282.000000     224.220000  
50%     305.000000     260.560000  
75%     328.000000     295.410000  
max     416.000000     460.630000

In [94]:
df.describe(include=['O'])

Churn Intl_Plan Vmail_Plan
count   3333      3333       3333
unique     2         2          2
top       no        no         no
freq    2850      3010       2411